config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pets#index'
  resources :pets, only:[:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: %w(dog cat rabbit snake turtle hamster monkey) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    @pet.update(pet_params)
    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :location_found, :found_at, :species)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostpetSkipActiveStorage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <h1>Found a pet ?</h1>
  <%= simple_form_for(@pet) do |f| %>
    <%= f.input :name %>
    <%= f.input :species, collection: %w(dog cat monkey rabbit) %>
    <%= f.input :location_found %>
    <%= f.input :found_at %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

<!--
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

 -->

app/views/pets/index.html.erb
<div class="container my-5">
  <h1>Pets</h1>
  <br>
  <% @pets.each do |pet| %>
    <p>
    <%= link_to pet.name, pet_path(pet) %>
    &middot;  <%= link_to "delete", pet_path(pet),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
    <% end %>
    </p>
  <hr>
  <%= link_to "Add a pet", new_pet_path %>
</div>

app/views/pets/new.html.erb
<div class="container my-5">
  <h1>Found a pet ?</h1>
  <%= simple_form_for(@pet) do |f| %>
    <%= f.input :name %>
    <%= f.input :species, collection: %w(dog cat monkey rabbit) %>
    <%= f.input :location_found %>
    <%= f.input :found_at %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

  <hr>
  <%= link_to "Home", root_path %>

</div>

app/views/pets/show.html.erb
<div class='container my-5'>
  <h1><%= @pet.name %></h1>
  <br>
  <p><strong>Species: </strong><%= @pet.species %></p>
  <p><strong>Location found: </strong><%= @pet.location_found %></p>
  <p><strong>Date found: </strong><%= @pet.found_at %></p>
  <hr>
  <%= link_to 'All Pets', pets_path %>
  <%= link_to 'Home', root_path %>
</div>